name       : nuvolaplayer
version    : 3.0.4
release    : 4
source     :
    - https://github.com/tiliado/nuvolaplayer/archive/3.0.4.tar.gz : 6577f96f305fd9a1d294c6f1a49b5d6a515dd42b026ce58ef89aeb19cd03349d
license    : BSD-2-Clause
component  : multimedia.audio
summary    : Cloud music integration for your desktop
description: |
    Nuvola Player is a runtime for web-based music streaming services providing more native user experience and integration with Linux desktop environments than usual web browsers can offer. It tries to feel and look like a native application as possible.
libsplit   : no
builddeps  :
    - pkgconfig(dioritegtk-0.2)
    - pkgconfig(glib-2.0)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(javascriptcoregtk-4.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libarchive)
    - pkgconfig(libnotify)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(python-2.7)
    - pkgconfig(vapigen)
    - pkgconfig(webkit2gtk-3.0)
    - pkgconfig(webkit2gtk-4.0)
    - vala
setup      : |
    CFLAGS="${CFLAGS} -I/usr/include/diorite-1.0"
    ./waf configure --prefix=/usr --libdir=%libdir%
build      : |
    ./waf build
install    : |
    ./waf install --no-system-hooks --destdir=$installdir
